spring:
  application:
    name: eureka-server
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: configserver:http://localhost:8888

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enable-self-preservation: false
